name: Deploy to Server

on:
  push:
    branches:
      - main     # Solo se ejecuta cuando haces push/merge a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 60
          port: 22
          script: |
            set -e
            cd /home/coopcb/api_cb/selenium_cb/
            git fetch --all
            git reset --hard origin/main
            docker compose up -d --build pdf-generator
